spring:
  application:
    name: ytt

  profiles:
    active: prod
    include: common, secret

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

    jmx:
      exposure:
        exclude: '*'

  endpoint:
    health:
      show-details: always
