spring:
  h2:
    console:
      enabled: true      # H2 콘솔을 활성화
      path: /h2-console  # H2 콘솔의 경로 설정

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DATABASE_TO_LOWER=TRUE   # H2 인메모리 데이터베이스를 사용
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update  # 스키마 자동 업데이트 (create, update, validate, none)
    show-sql: true      # 쿼리 로그를 출력하도록 설정
    format_sql: true    # 쿼리 로그를 보기 좋게 포맷팅

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG  # 쿼리 로그를 디버그 레벨로 출력